# Generated by Django 4.2.3 on 2023-07-13 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30, verbose_name="제목")),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="postImage", verbose_name="이미지"
                    ),
                ),
                ("date", models.DateField(verbose_name="기간")),
            ],
        ),
    ]
