# Generated by Django 4.2.3 on 2023-07-14 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="comment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="blogapp.commentbox",
                verbose_name="댓글",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="post",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="blogapp.post",
                verbose_name="포스트",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="rating",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="postImage", verbose_name="이미지"
            ),
        ),
    ]
