# Generated by Django 4.2.3 on 2023-07-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='pf_img/')),
                ('portfolio', models.FileField(blank=True, null=True, upload_to='pofol/')),
                ('school', models.CharField(blank=True, default='', max_length=30)),
                ('bio', models.CharField(blank=True, default='', max_length=500)),
                ('star', models.BooleanField(default=True)),
                ('review', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
