# Generated by Django 4.2.3 on 2023-07-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='review',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='star',
            field=models.BooleanField(default=True),
        ),
    ]
